#!/bin/sh

# Basic zsh completion setup
autoload -Uz compinit
compinit -i

# Enable completion caching
zstyle ':completion:*' cache-path ~/.zsh/cache
zstyle ':completion:*' use-cache true

# Case-insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# Better completion selection
zstyle ':completion:*' menu select
